//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIM.Web.Admin.PersonalInfoServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:trackable-entities:service", ConfigurationName="PersonalInfoServiceReference.IPersonlInfoService")]
    public interface IPersonlInfoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IPersonlInfoService/GetPersonalInfoes", ReplyAction="urn:trackable-entities:service/IPersonlInfoService/GetPersonalInfoesResponse")]
        AIM.Service.Entities.Models.PersonalInfo[] GetPersonalInfoes();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IPersonlInfoService/GetPersonalInfoes", ReplyAction="urn:trackable-entities:service/IPersonlInfoService/GetPersonalInfoesResponse")]
        System.Threading.Tasks.Task<AIM.Service.Entities.Models.PersonalInfo[]> GetPersonalInfoesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IPersonlInfoService/GetPersonalInfo", ReplyAction="urn:trackable-entities:service/IPersonlInfoService/GetPersonalInfoResponse")]
        AIM.Service.Entities.Models.PersonalInfo GetPersonalInfo(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IPersonlInfoService/GetPersonalInfo", ReplyAction="urn:trackable-entities:service/IPersonlInfoService/GetPersonalInfoResponse")]
        System.Threading.Tasks.Task<AIM.Service.Entities.Models.PersonalInfo> GetPersonalInfoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IPersonlInfoService/UpdatePersonalInfo", ReplyAction="urn:trackable-entities:service/IPersonlInfoService/UpdatePersonalInfoResponse")]
        AIM.Service.Entities.Models.PersonalInfo UpdatePersonalInfo(AIM.Service.Entities.Models.PersonalInfo entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IPersonlInfoService/UpdatePersonalInfo", ReplyAction="urn:trackable-entities:service/IPersonlInfoService/UpdatePersonalInfoResponse")]
        System.Threading.Tasks.Task<AIM.Service.Entities.Models.PersonalInfo> UpdatePersonalInfoAsync(AIM.Service.Entities.Models.PersonalInfo entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IPersonlInfoService/CreatePersonalInfo", ReplyAction="urn:trackable-entities:service/IPersonlInfoService/CreatePersonalInfoResponse")]
        AIM.Service.Entities.Models.PersonalInfo CreatePersonalInfo(AIM.Service.Entities.Models.PersonalInfo entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IPersonlInfoService/CreatePersonalInfo", ReplyAction="urn:trackable-entities:service/IPersonlInfoService/CreatePersonalInfoResponse")]
        System.Threading.Tasks.Task<AIM.Service.Entities.Models.PersonalInfo> CreatePersonalInfoAsync(AIM.Service.Entities.Models.PersonalInfo entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IPersonlInfoService/DeletePersonalInfo", ReplyAction="urn:trackable-entities:service/IPersonlInfoService/DeletePersonalInfoResponse")]
        bool DeletePersonalInfo(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IPersonlInfoService/DeletePersonalInfo", ReplyAction="urn:trackable-entities:service/IPersonlInfoService/DeletePersonalInfoResponse")]
        System.Threading.Tasks.Task<bool> DeletePersonalInfoAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPersonlInfoServiceChannel : AIM.Web.Admin.PersonalInfoServiceReference.IPersonlInfoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonlInfoServiceClient : System.ServiceModel.ClientBase<AIM.Web.Admin.PersonalInfoServiceReference.IPersonlInfoService>, AIM.Web.Admin.PersonalInfoServiceReference.IPersonlInfoService {
        
        public PersonlInfoServiceClient() {
        }
        
        public PersonlInfoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonlInfoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonlInfoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonlInfoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AIM.Service.Entities.Models.PersonalInfo[] GetPersonalInfoes() {
            return base.Channel.GetPersonalInfoes();
        }
        
        public System.Threading.Tasks.Task<AIM.Service.Entities.Models.PersonalInfo[]> GetPersonalInfoesAsync() {
            return base.Channel.GetPersonalInfoesAsync();
        }
        
        public AIM.Service.Entities.Models.PersonalInfo GetPersonalInfo(int id) {
            return base.Channel.GetPersonalInfo(id);
        }
        
        public System.Threading.Tasks.Task<AIM.Service.Entities.Models.PersonalInfo> GetPersonalInfoAsync(int id) {
            return base.Channel.GetPersonalInfoAsync(id);
        }
        
        public AIM.Service.Entities.Models.PersonalInfo UpdatePersonalInfo(AIM.Service.Entities.Models.PersonalInfo entity) {
            return base.Channel.UpdatePersonalInfo(entity);
        }
        
        public System.Threading.Tasks.Task<AIM.Service.Entities.Models.PersonalInfo> UpdatePersonalInfoAsync(AIM.Service.Entities.Models.PersonalInfo entity) {
            return base.Channel.UpdatePersonalInfoAsync(entity);
        }
        
        public AIM.Service.Entities.Models.PersonalInfo CreatePersonalInfo(AIM.Service.Entities.Models.PersonalInfo entity) {
            return base.Channel.CreatePersonalInfo(entity);
        }
        
        public System.Threading.Tasks.Task<AIM.Service.Entities.Models.PersonalInfo> CreatePersonalInfoAsync(AIM.Service.Entities.Models.PersonalInfo entity) {
            return base.Channel.CreatePersonalInfoAsync(entity);
        }
        
        public bool DeletePersonalInfo(int id) {
            return base.Channel.DeletePersonalInfo(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeletePersonalInfoAsync(int id) {
            return base.Channel.DeletePersonalInfoAsync(id);
        }
    }
}
